title: Authenticator App
description: Secure and fast Two-Factor Authentication manager for iPhone, iPad, iPod, Apple Watch and macOS.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman

available_on_app_store: true
iOS_url: https://apps.apple.com/app/id1538761576#?platform=iphone
macOS_url: https://apps.apple.com/app/id1538761576#?platform=mac

test_flight_url: https://testflight.apple.com/join/a20tIGsB

privacy_url: ./PrivacyPolicy.html
terms_of_service_url: ./TermsOfService.html
support_mail: mailto:support@2stable.com

# patch  for privacy and terms
APP_NAME: Authenticator

appstore: 
  - src: ./assets/img/badge-download-on-the-app-store.svg
    alt: iOS Apple App Badge
    url: https://apps.apple.com/app/id1538761576#?platform=iphone

  - src: ./assets/img/badge-download-on-the-mac-app-store.svg
    alt: macOS Apple App Badge
    url: https://apps.apple.com/app/id1538761576#?platform=iphone


features: 
  - title: No Account Required
    details: Easy to set up. You have to remember just one password.
    image: https://dvzvtsvyecfyp.cloudfront.net/static/img/twemoji/2728.svg

  - title: Biometric Authentication
    details: Unlock Authenticator without typing your passphrase using Touch or Face ID.
    image: https://dvzvtsvyecfyp.cloudfront.net/static/img/twemoji/1f440.svg

  - title: Sync & Backup
    details: All data is automatically backed up and synced across all devices via iCloud.
    image: https://dvzvtsvyecfyp.cloudfront.net/static/img/twemoji/1f9f2.svg

  - title: Secure & Private
    details: All data is encrypted even if is stored in iCloud, so you never have to worry about nasty hackers.
    image: https://dvzvtsvyecfyp.cloudfront.net/static/img/twemoji/1f510.svg

  - title: User Friendly
    details: Native experience on all Apple devices. Data Sync, Gestures, Widgets, Dark Mode and more!
    image: https://dvzvtsvyecfyp.cloudfront.net/static/img/twemoji/1f98b.svg

  - title: Friendly Support
    details: Got a question? <a href="mailto:support@2stable.com">Get in touch</a> with us at any time. We're a friendly team of four :)
    image: https://dvzvtsvyecfyp.cloudfront.net/static/img/twemoji/1f432.svg

features-banner:
  - title: Protect your accounts with an extra layer of security
    details: Authenticator is a simple, <a href="https://en.wikipedia.org/wiki/Two-factor_authentication">two-factor authentication</a> app. It helps keep your online accounts secure by generating unique one-time passwords.
