title: Authenticator App
description: Secure and fast Two-Factor Authentication manager for iPhone, iPad, iPod, Apple Watch and macOS.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman

available_on_app_store: true

iOS_url: https://apps.apple.com/app/id1538761576#?platform=iphone
macOS_url: https://apps.apple.com/app/id1538761576#?platform=mac

privacy_url: ./PrivacyPolicy.html
terms_of_service_url: ./TermsOfService.html
mail_to_url: support@2stable.com
