title: "Authenticator: Widget & Backup"
description: Secure and fast Two-Factor Authentication manager for iPhone, iPad, iPod, Apple Watch and macOS.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman

ios_url: https://apps.apple.com/app/id1538761576#?platform=iphone
macos_url: https://apps.apple.com/app/id1538761576#?platform=mac