title: "Authenticator: Widget & Backup"
description: Secure and fast two-factor authentication manager for iPhone, iPad, iPod, Apple Watch and macOS.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
github.zip_url: https://apps.apple.com/app/id1538761576
zip_url: https://apps.apple.com/app/id1538761576